fail_fast: false
minimum_pre_commit_version: "2.6.0"
repos:
  # Standard file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: check-case-conflict
      - id: mixed-line-ending
        args: ['--fix=lf']

  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.37.0
    hooks:
      - id: markdownlint
        args: ['--fix']
        files: \.(md|markdown)$

  # JSON formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        types: [json]
        args: ['--write']

  # JavaScript/Node.js linting (if you have JS files)
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.51.0
    hooks:
      - id: eslint
        files: \.(js|ts)$
        additional_dependencies: [eslint@8.51.0]

  # Custom hook for README generator test
  - repo: local
    hooks:
      - id: readme-generator-test
        name: Test README Generator
        entry: npm
        args: ['run', 'test:readme-generator']
        language: system
        files: '^(BLANK_README\.md|configs/.*\.json|scripts/generate-readme\.js)$'
        pass_filenames: false
