fail_fast: false
minimum_pre_commit_version: "2.6.0"
repos:
  # Standard file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: check-case-conflict
      - id: mixed-line-ending
        args: ['--fix=lf']

  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
        args: ['--fix']
        exclude: '^CHANGELOG\.md$'

  # JSON formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        types: [json]
        args: ['--write']

  # README Generator validation
  - repo: https://github.com/actuarysailor/pre-commit-readme-generator
    rev: v1.1.3
    hooks:
      - id: readme-generator-test
        args: [configs/example.json, README.md, BLANK_README.md, --debug]
